env=DEV
hdfs.path=hdfs\://rdev/user/semantic
source.db.user=loadTest
source.db.password=123456
source.url=jdbc:sqlserver://10.0.122.203:1433;databaseName=Nawaf_Test;encrypt=false;
source.db.type=sqlserver
cmc.db.user=PipelineGen
cmc.db.password=123456
cmc.db.url=jdbc\:sqlserver\://10.0.122.143;databaseName\=NDB_DEV_META;encrypt=false;
cmc.agency.id=21
cmc.dataset.id=111
cmc.table.name=Consumption_Schema
kebro.principal=semantic@NICINT.MOI.GOV
partition.column=